build:
  run_tests:
    image: python:3.5-slim
    commands:
      - pip install -r requirements_test.txt
      - flake8 failsafe/ tests/
      - python setup.py test

  set_dev_version:
    image: python:3.5-slim
    commands:
      - echo 'dev-$$BRANCH' > version.txt
    when:
      branch: '!master'

publish:
  pypi:
    repository: https://repository.prod.aws.skyscnr.com/artifactory/api/pypi/pypi
    username: $$pypi_username
    password: $$pypi_password
